const Departements = [
    { label: 'Administration et Organisation scolaire', value: 1 },
    { label: 'Al-Charia', value: 2 },
    { label: 'Al-Logha Al Arabia', value: 3 },
    { label: 'Anesthésie-Réanimation', value: 4 },
    { label: 'Appareil Digestif', value: 5 },
    { label: 'Appareil et Maladies Respiratoire', value: 6 },
    { label: 'Appareil Génito-Urinaires', value: 7 },
    { label: 'Appareil Locomoteur', value: 8 },
    { label: 'Application Industrielle', value: 9 },
    { label: 'Arabe-Allemand-Français', value: 10 },
    { label: 'Arabe-Anglais-Français', value: 11 },
    { label: 'Arabe-Espagnol-français', value: 12 },
    { label: 'Arabe-Français-Anglais', value: 13 },
    { label: 'Biologie', value: 14 },
    { label: 'Biologie et Matières Fondamentales', value: 15 },
    { label: 'Botanique', value: 16 },
    { label: 'Cardiologie', value: 17 },
    { label: 'Chimie', value: 18 },
    { label: 'Chirurgie', value: 19 },
    { label: 'Commerce', value: 20 },
    { label: 'Didactique des Langues', value: 21 },
    { label: 'Didactique des Sciences Exactes', value: 22 },
    { label: 'Didactique des Sciences Humaines', value: 23 },
    { label: 'Droit privé', value: 24 },
    { label: 'Droit public', value: 25 },
    { label: 'Economie/sciences économiques', value: 26 },
    { label: 'Education physique', value: 27 },
    { label: 'Energétique', value: 28 },
    { label: 'Etudes Amazighes', value: 29 },
    { label: 'Etudes Hispano-Lusophones', value: 30 },
    { label: 'Etudes Islamiques', value: 31 },
    { label: 'Fondamental de l\'Éducation', value: 32 },
    { label: 'Génie Agroalimentaire', value: 33 },
    { label: 'Génie Civil', value: 34 },
    { label: 'Génie de l\'Environnement', value: 35 },
    { label: 'Génie des Procédés', value: 36 },
    { label: 'Génie Électrique', value: 37 },
    { label: 'Genie Industriel', value: 38 },
    { label: 'Génie Mécanique', value: 39 },
    { label: 'Génie Minéral', value: 40 },
    { label: 'Génie Modélisation et Informatique Scientifique', value: 41 },
    { label: 'Génie Télécommunications et Réseaux', value: 42 },
    { label: 'Génie Urbain et Environnement', value: 43 },
    { label: 'Géographie', value: 44 },
    { label: 'Géologie', value: 45 },
    { label: 'Gestion', value: 46 },
    { label: 'Glandes Endocrines et Revêtement', value: 47 },
    { label: 'Gyneco-Obstérique', value: 48 },
    { label: 'Histoire', value: 49 },
    { label: 'Imagerie Médicale', value: 50 },
    { label: 'Informatiques', value: 51 },
    { label: 'Langue et Littérature Allemandes', value: 52 },
    { label: 'Langue et Littérature Anglaises', value: 53 },
    { label: 'Langue et Littérature Arabes', value: 54 },
    { label: 'Langue et Littérature Espagnoles', value: 55 },
    { label: 'Langue et Littérature Françaises', value: 56 },
    { label: 'Langue et Littérature Italiennes', value: 57 },
    { label: 'Langue et Littérature Russes', value: 58 },
    { label: 'Management', value: 59 },
    { label: 'Mathématiques', value: 60 },
    { label: 'Médecine', value: 61 },
    { label: 'Médecine Sociale et Communautaire', value: 62 },
    { label: 'Mère-enfant', value: 63 },
    { label: 'Odontologie Chirurgicale', value: 64 },
    { label: 'Odontologie Concervatrice', value: 65 },
    { label: 'Orthopédie Dento-Faciale', value: 66 },
    { label: 'Ossoul Eddine', value: 67 },
    { label: 'Oto-Neuro-Ophtalmologie', value: 68 },
    { label: 'Parodontologie', value: 69 },
    { label: 'Pédiatrie', value: 70 },
    { label: 'Pédodontie Prévention', value: 71 },
    { label: 'Philosophie', value: 72 },
    { label: 'Physique', value: 73 },
    { label: 'Phytologie', value: 74 },
    { label: 'Prothèse Adjointe', value: 75 },
    { label: 'Prothèse Conjointe', value: 76 },
    { label: 'Prothèse Maxillo-Faciale', value: 77 },
    { label: 'Psychiatrie et Psychologie Médicale', value: 78 },
    { label: 'Psychologie', value: 79 },
    { label: 'Psychologie de l\'Éducation', value: 80 },
    { label: 'Radiologie', value: 81 },
    { label: 'Sciences biomedicales', value: 82 },
    { label: 'Science des matériaux', value: 83 },
    { label: 'Sciences de l\'éducation', value: 84 },
    { label: 'Sciences de la Terre', value: 85 },
    { label: 'Sciences du Médicament', value: 86 },
    { label: 'Sciences Fondamental Precliniques', value: 87 },
    { label: 'Sociologie', value: 88 },
    { label: 'Technique de Management', value: 89 },
    { label: 'Technique d\'Expression et de Communication/langue et communication', value: 90 },
    { label: 'Techniques d\'Analyse et Contrôle de Qualité', value: 91 },
    { label: 'Techniques de Communication Commerciale', value: 92 },
    { label: 'Techniques de Management', value: 93 },
    { label: 'Technologie de l\'Éducation', value: 94 },
    { label: 'Traduction', value: 95 },
    { label: 'Urgence Médico-Chirurgicales', value: 96 },
    { label: 'Zoologie', value: 97 },
];

export default Departements;
