const Diplomes = [
    { label: 'SANS DIPLOME OU DIPLOME INCONNU', value: 0, arabic: 'بدون دبلوم او دبلوم مجهول' },
    { label: 'AUTRES DIPLOMES', value: 90, arabic: 'شهادات اخرى' },
    { label: 'BACCALAUREAT OU EQUIVALENT', value: 3, arabic: 'الباكلوريا او ما يعادلها' },
    { label: 'C.E.S (CERTIFICAT D\'ETUDES SPECIALISEES)', value: 65, arabic: 'شهادة الدراسات المختصة' },
    { label: 'C.E.U.S (CERTIFICAT D\'ETUDES UNIVER. SPECIAL)', value: 64, arabic: 'شهادة الدراسات الجامعية المختصة' },
    { label: 'CEA (certificat des études approffondies)', value: 83, arabic: 'شهادة الدراسات المعمفة' },
    { label: 'CERTIFICAT DE L\'ENSEINEMENT PRIMAIRE', value: 1, arabic: 'شــهادة التعليم الإبتدائي' },
    { label: 'CERTIFICAT DE L\'ENSEINEMENT SECONDAIRE', value: 2, arabic: 'شهادة التعليم الثانوي' },
    { label: 'D,E,A OU EQUIVALENT', value: 60, arabic: 'دبلوم الدراسات المعمقة او ما يعادله' },
    { label: 'D.E.S.S (DIPLOM D\'ETUDES SUPER. SPECIALISEES)', value: 63, arabic: 'دبلوم الدراسات العليا المختصة' },
    { label: 'DESA (diplôme des études supérieur approffondies)', value: 82, arabic: 'دبلوم الدراسات العليا المعمفة' },
    { label: 'DIPLOME D\'AGREGATION DES ECOLES NATIONALES', value: 69, arabic: 'دبلومالتبريزللمدارس الوطنية' },
    { label: 'DIPLÔME ENCG', value: 78, arabic: 'دبلوم المدارس الوطنية للتجارة و التسيير' },
    { label: 'DOCTORAT DE 3EME CYCLE OU EQUIVALENT', value: 70, arabic: 'دكتوراة السلك الثالث او ما يعادلها' },
    { label: 'DOCTORAT D\'ETAT OU EQUIVALENT', value: 71, arabic: 'دكتوراة الدولة او ما يعادلها' },
    { label: 'DOCTORAT D\'UNIVERSITE(FRANCE)', value: 75, arabic: 'دكتوراه الجامعية (الفرنسية)' },
    { label: 'DOCTORAT EN MEDECINE', value: 72, arabic: 'دكتوراة في الطب' },
    { label: 'DOCTORAT EN MEDECINE DENTAIRE', value: 74, arabic: 'دكتوراة في طب الاسنان' },
    { label: 'DOCTORAT EN PHARMACIE', value: 73, arabic: 'دكتوراة في الصيدلة' },
    { label: 'DT (diplôme de technologie)', value: 85, arabic: 'دبلوم التكنلوجيا' },
    { label: 'DUT (diplôme universitaire de technologie)', value: 84, arabic: 'الدبلوم الجامعي للتكنلوجيا' },
    { label: 'HABILITATION A DIRIGER DES RECHERCHES (FRANCE)', value: 77, arabic: 'التأهيل للاشراف على أبحاث' },
    { label: 'HABILITATION UNIVERSITAIRE(MAROC)', value: 76, arabic: 'التأهيل الجامعي' },
    { label: 'INFORMATISTE OU EQUIVALENT', value: 50, arabic: 'اعلامي او ما يعادله' },
    { label: 'INFORMATISTE SPECIALISE OU EQUIVALENT', value: 61, arabic: 'إعلامي مختص او ما يعادله' },
    { label: 'INGENIEUR D\'APPLICATION OU EQUIVALENT', value: 51, arabic: 'مهندس تطبيق او ما يعادله' },
    { label: 'INGENIEUR D\'ETAT OU EQUIVALENT', value: 62, arabic: 'مهندس الدولة او مايعادله' },
    { label: 'LA LICENCE OU EQUIVALENT', value: 41, arabic: 'الإجازة أو ما يعادلها' },
    { label: 'MASTER', value: 79, arabic: 'ماستر' },
    { label: 'MASTER SCIENCES ET TECHNIQUES', value: 81, arabic: 'ماستر العلوم و التفنيات' },
    { label: 'MASTER SPECIALISE', value: 80, arabic: 'ماستر مختص' },
    { label: 'PREMIER CYCLE UNIVERSITAIRE OU EQUIVALENT', value: 40, arabic: 'السلك الاول الجامعي او ما يعادله' },
    { label: 'PROGRAMEUR', value: 99, arabic: 'مــبرمــج' }
];

export default Diplomes;
