
    const Provinces = [
  { label: 'Agadir-Ida-Ou-Tanane', value: 1 },
  { label: 'Al Haouz', value: 41 },
  { label: 'Al Hoceima', value: 51 },
  { label: 'Meknès', value: 61 },
  { label: 'Aousserd', value: 66 },
  { label: 'Assa-Zag', value: 71 },
  { label: 'Azilal', value: 81 },
  { label: 'Béni Mellal', value: 91 },
  { label: 'Benslimane', value: 111 },
  { label: 'Berkane', value: 113 },
  { label: 'Berrechid', value: 117 },
  { label: 'Boujdour', value: 121 },
  { label: 'Boulemane', value: 131 },
  { label: 'Casablanca', value: 141 },
  { label: 'Chefchaouen', value: 151 },
  { label: 'Chichaoua', value: 161 },
  { label: 'Chtouka-Ait Baha', value: 163 },
  { label: 'Driouch', value: 167 },
  { label: 'El Hajeb', value: 171 },
  { label: 'El Jadida', value: 181 },
  { label: 'El Kelâa des Sraghna', value: 191 },
  { label: 'Errachidia', value: 201 },
  { label: 'Essaouira', value: 211 },
  { label: 'Es-Semara', value: 221 },
  { label: 'Fahs-Anjra', value: 227 },
  { label: 'Fès', value: 231 },
  { label: 'Figuig', value: 251 },
  { label: 'Fquih Ben Salah', value: 255 },
  { label: 'Guelmim', value: 261 },
  { label: 'Guercif', value: 265 },
  { label: 'Ifrane', value: 271 },
  { label: 'Inezgane-Ait Melloul', value: 273 },
  { label: 'Jerada', value: 275 },
  { label: 'Kénitra', value: 281 },
  { label: 'Khémisset', value: 291 },
  { label: 'Khénifra', value: 301 },
  { label: 'Khouribga', value: 311 },
  { label: 'Laâyoune', value: 321 },
  { label: 'Larache', value: 331 },
  { label: 'Marrakech', value: 351 },
  { label: 'Médiouna', value: 355 },
  { label: 'Midelt', value: 363 },
  { label: 'Mohammadia', value: 371 },
  { label: 'Nador', value: 381 },
  { label: 'Nouaceur', value: 385 },
  { label: 'Oued Ed-Dahab', value: 391 },
  { label: 'Ouarzazate', value: 401 },
  { label: 'Ouezzane', value: 405 },
  { label: 'Oujda-Angad', value: 411 },
  { label: 'Rabat', value: 421 },
  { label: 'Rehamna', value: 427 },
  { label: 'Safi', value: 431 },
  { label: 'Salé', value: 441 },
  { label: 'Sefrou', value: 451 },
  { label: 'Settat', value: 461 },
  { label: 'Sidi Bennour', value: 467 },
  { label: 'Sidi Ifni', value: 473 },
  { label: 'Sidi Kacem', value: 481 },
  { label: 'Sidi Slimane', value: 491 },
  { label: 'Skhirate-Témara', value: 501 },
  { label: 'Tanger-Assilah', value: 511 },
  { label: 'Tan-Tan', value: 521 },
  { label: 'Taounate', value: 531 },
  { label: 'Taourirt', value: 533 },
  { label: 'Tarfaya', value: 537 },
  { label: 'Taroudannt', value: 541 },
  { label: 'Tata', value: 551 },
  { label: 'Taza', value: 561 },
  { label: 'Tétouan', value: 571 },
  { label: "M'Diq-Fnideq", value: 573 },
  { label: 'Tinghir', value: 577 },
  { label: 'Tiznit', value: 581 },
  { label: 'Youssoufia', value: 585 },
  { label: 'Zagora', value: 587 },
  { label: 'Moulay Yacoub', value: 591 },
  { label: 'province non spécifiée', value: 998 },
  { label: 'Provinces étrangères', value: 999 }
];

export default Provinces;